apiVersion: v1
kind: Service
metadata:
  name: {{ include "unbound.fullname" . }}
  labels:
    {{- include "unbound.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 53
      protocol: TCP
      name: tcp-dns
    - port: {{ .Values.service.port }}
      targetPort: 53
      protocol: UDP
      name: udp-dns
  selector:
    {{- include "unbound.selectorLabels" . | nindent 4 }}
