{{- if .Values.persistenceVolume.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
    name: nextcloud-storage
spec:
    storageClassName: {{ .Values.persistenceVolume.storageClassName }}
    capacity:
        storage: {{ .Values.persistenceVolume.storage }}
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: {{ .Values.persistenceVolume.hostPath }}
{{- end }}