{{- if .Values.persistenceVolume.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: codeserver-storage
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.persistenceVolume.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistenceVolume.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistenceVolume.storage }}
{{- end }}